### PR TITLE
Don't stop the loop in `run_until_complete()` on `SystemExit` and `KeyboardInterrupt` exceptions

### LINKED ISSUE #336: `loop.run_until_complete` raises `RuntimeError` after catching `SystemExit`
* **uvloop version**: 0.14.0
* **Python version**: 3.8.2
* **Platform**: Ubuntu 18.04
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: Yes
* **Does uvloop behave differently from vanilla asyncio? How?**: Yes, vanilla `asyncio` doesn't raise for this code

**Reproduction code:**
```py
import asyncio
import sys
import uvloop

asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())
loop = asyncio.new_event_loop()

async def x():
    sys.exit(1)

return_code = 0
try:
    loop.run_until_complete(x())
except SystemExit as exc:
    return_code = exc.code
finally:
    loop.run_until_complete(asyncio.sleep(1))
    sys.exit(return_code)
```
**Traceback:**
```
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    loop.run_until_complete(asyncio.sleep(1))
  File "uvloop/loop.pyx", line 1454, in uvloop.loop.Loop.run_until_complete
RuntimeError: Event loop stopped before Future completed.
```

Same happens when `KeyboardInterrupt` is raised - vanilla `asyncio` handles both of these here: https://github.com/python/cpython/blob/master/Lib/asyncio/base_events.py#L187-L190

### PR DESCRIPTION
**Pull request by jack1142**
Fixes #336

### CODE REVIEW

**Comment by 1st1** [comment]
Can you add a unittest?

**Comment by jack1142** [comment]
@1st1 I added the unit test based on [CPython's equivalent](https://github.com/python/cpython/blob/003708bcf8f2c58d4b65f68318acf164d713e008/Lib/test/test_asyncio/test_base_events.py#L850-L872) and rebased the PR's branch on top of master.
Let me know if there's anything else you would want me to do.

**Comment by jack1142** [comment]
I've rebased this on top of `master` since it looks like there's a new required check + it's been moved to the project board it seems. I'm still available to do any additional changes if needed so just let me know if needed.

I'm also mentioning this since I'm hoping this could get included in the next release, whenever it's ready of course :)

**Comment by fantix** [comment]
Thanks for the PR! The thing is the test is NOT failing without the fix, I'm looking into it now.

**Review by fantix — APPROVED** [review]

**Pull request merged**
