### PR TITLE
Fix tests invocation on release CI worklow

### PR DESCRIPTION
**Pull request by ben9923**
Looking at the current release flow I discovered it has 2 issues.
1. Newly added test seems to make it fail (Added in #310, same with #491 which moved it to a different module).
2. `musllinux` builds fail on dependency installation.

This PR should adress the former (A PR for the latter will follow):
I also employed the discovery CLI command of `unittest` rather than the custom suite  creation script.
Kept a more-standard-named `__main__` as a legacy, which replaces the `__init__`, but its usage is pretty much discouraged (Can't mess with `unittest` flags, for example).

Error when running tests via `cibuildwheel`:
```
======================================================================
ERROR: test_libuv_get_loop_t_ptr (test_libuv_api.Test_UV_libuv)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/project/tests/test_libuv_api.py", line 16, in test_libuv_get_loop_t_ptr
    from tests import cython_helper
ModuleNotFoundError: No module named 'tests'
```

### No regression in tests workflow:
`master` test workflow:
https://github.com/ben9923/uvloop/actions/runs/2896500138

`fix-wheel-tests` test workflow:
https://github.com/ben9923/uvloop/actions/runs/2896506757

### A different error (later in the process) on release workflow:
`master` release workflow:
https://github.com/ben9923/uvloop/actions/runs/2896500137

`fix-wheel-tests` release workflow:
https://github.com/ben9923/uvloop/actions/runs/2896506756

### CODE REVIEW

**Comment by ben9923** [comment]
@fantix Rebased the PR so GitHub doesn't complain ahead of merging, and tests failed for some reason.
It doesn't appear to be related to my changes, could the tests be a bit flakey?

Seems like I have no permission to re-run it myself, could you either alter the settings somehow or just re-run yourself? :)

Wish this one could be merged soon, cause I also want to add `musllinux` wheels in time for the next release.
Anyway this PR is a blocker for the release, without it `cibuildwheel` will fail.

**Comment by fantix** [comment]
Thank you @ben9923 for keeping this up to date! I'm testing the release CI in the `ci` branch with this PR.

**Comment by ben9923** [comment]
@fantix Thanks for having a look!
I see you caught the necessary `cibuildwheel` upgrade for 3.11 haha, planned to push it separately.

Didn't open a PR for `musllinux` yet as some tests are failing, so this one will only get you through `manylinux` build.

**Comment by fantix** [comment]
> Edit: Those dns/tcp errors you see on musl are exactly the ones I saw locally

Cool, I'll create a new PR to fix them.

**Review by fantix — APPROVED** [review]

**Pull request merged**
