### PR TITLE
Add Python 3.8 classifier

### PR DESCRIPTION
**Pull request by naglis**

### CODE REVIEW

**Comment by wyqsmith** [comment]
Sometimes It cannot work with `Python 3.8` correctly in some scenarios.

**Comment by 1st1** [comment]
> Sometimes It cannot work with Python 3.8 correctly in some scenarios.

Would you mind enumerating those scenarios?

**Comment by wyqsmith** [comment]
@1st1 So sorry for the late reply...

I ran into some problems but They seem to be caused by another lib `aioredis`...

Feel so sorry about this issue...

**Comment by fantix** [comment]
Thanks for the PR! This is included in [#376](https://github.com/MagicStack/uvloop/pull/376/commits/c2c838069d33c646f713d860a57fa7440e4d4c54#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R316).

**Pull request closed without merging**
