### PR TITLE
Fixup CI

### PR DESCRIPTION
**Pull request by altendky**

### CODE REVIEW

**Comment by altendky** [comment]
https://github.com/MagicStack/uvloop/actions/runs/3721134010/jobs/6311076170#step:7:567
```
153, in find_plugins
2022-12-17T17:56:18.4586070Z     self.check_plugins = plugin_manager.Checkers(local_plugins.extension)
2022-12-17T17:56:18.4586700Z   File "/Users/runner/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/flake8/plugins/manager.py", line 357, in __init__
2022-12-17T17:56:18.4587070Z     self.namespace, local_plugins=local_plugins
2022-12-17T17:56:18.4587670Z   File "/Users/runner/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/flake8/plugins/manager.py", line 238, in __init__
2022-12-17T17:56:18.4588030Z     self._load_entrypoint_plugins()
2022-12-17T17:56:18.4588650Z   File "/Users/runner/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/flake8/plugins/manager.py", line 254, in _load_entrypoint_plugins
2022-12-17T17:56:18.4589070Z     eps = importlib_metadata.entry_points().get(self.namespace, ())
2022-12-17T17:56:18.4589490Z AttributeError: 'EntryPoints' object has no attribute 'get'
```

**Comment by altendky** [comment]
Maybe just skip the flake8 check in 3.7 so we can use the latest?  It is 3.8.1+.  Or stick with flake8 5 as this has now.

**Comment by altendky** [comment]
Might be worth a nightly build as well to catch failures early?  I haven't really dug in but I'm guessing a setuptools update broke this.

**Comment by altendky** [comment]
https://github.com/MagicStack/uvloop/actions/runs/3721513697/jobs/6311716324#step:7:647
```
FAIL: test_call_later_rounding (test_base.TestBaseAIO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/uvloop/uvloop/tests/test_base.py", line 220, in test_call_later_rounding
    self.assertGreaterEqual(finished - started, 69)
AssertionError: 65 not greater than or equal to 69
```

**Comment by altendky** [comment]
Kick ci

**Comment by altendky** [comment]
I haven't managed to recreate the hangs locally yet, so I guess I'll try to debug here in CI.

**Comment by altendky** [comment]
https://github.com/MagicStack/uvloop/actions/runs/3722977120/jobs/6314201846#step:7:582
```python-traceback
ERROR: test_create_unix_server_ssl_1 (test_unix.Test_AIO_UnixSSL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/uvloop/uvloop/tests/test_unix.py", line 599, in test_create_unix_server_ssl_1
    self.loop.run_until_complete(start_server())
  File "/Users/runner/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/runner/work/uvloop/uvloop/tests/test_unix.py", line 591, in start_server
    await asyncio.wait_for(asyncio.gather(*tasks), TIMEOUT)
  File "/Users/runner/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
```

**Comment by altendky** [comment]
Looks like `test_remote_shutdown_receives_trailing_data()` might be the culprit.  Maybe tomorrow I'll try undoing the other difference narrowing changes I've made since they don't seem relevant.

**Comment by altendky** [comment]
https://github.com/MagicStack/uvloop/actions/runs/3725634404/jobs/6318565550#step:8:948
```python-traceback
FAIL: test_call_later_rounding (test_base.TestBaseAIO.test_call_later_rounding)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/uvloop/uvloop/tests/test_base.py", line 220, in test_call_later_rounding
    self.assertGreaterEqual(finished - started, 69)
AssertionError: 65 not greater than or equal to 69
```

**Comment by altendky** [comment]
kick ci

**Comment by altendky** [comment]
I think the current state here is worth considering.

1) Skips `test_remote_shutdown_receives_trailing_data()` in the cases where it is causing hangs.  Certainly this should be fixed, but I think it might be appropriate to get CI back into a generally functional state sooner than later.
2) Increases output around the flake8 and mypy failure cases, specifically including the exception text (no traceback) and the stderr.
3) Updates flake8 to the last version supporting Python 3.7 and a corresponding pycodestyle version.  Perhaps another PR should update flake8 to latest and skip running that test on 3.7.

I certainly didn't try all the permutations, but I tried going back on a few points to try to identify a trigger for the test hangs that had changed since the last successful run.  No success identifying such a trigger.

* backup up dependency versions to match the last successful build at https://github.com/MagicStack/uvloop/actions/runs/3095350858/jobs/5009673734
* use `ubuntu-20.04`
* added aiohttp install for 3.11
* used non-prerelease 3.11

I tried running locally including calling the tests in a few different ways and failed to trigger a hang.  Local is Ubuntu 20.04 Linux.

I've also noted above a couple different testing flakes that I've seen while running here.

Separately, with green CI available, I would expect to submit PRs for:

1) GitHub managed workflow concurrency (cancel old PR runs when a new commit is pushed)
2) Job timeouts at 30 minutes
3) Using released Python 3.11
4) Automatic tracking of pre-release through release Pythons without updating for each version.
5) Latest flake8 skipped on Python <3.7
6) Install aiohttp for Python 3.11
7) Make `master` look more like the `win` branch in terms of `system.pxd` to reduce future conflicts between the two branches.
8) Setup daily builds to more quickly identify these failures that just start happening.  Then we know sooner, have a reference log available (not expired and removed by GitHub), and the diff between working and not is smaller.

Other points of interest that I don't know how to do already but might work on would be Windows support (I see the existing branch and comments about preferred next steps) and fixing the hanging `test_remote_shutdown_receives_trailing_data()` test.

**Comment by altendky** [comment]
Kicking CI to make sure it is fresh.

**Comment by altendky** [comment]
We constrain pyopenssl but not cryptography and this, along with their deps not being constrained, allowed for incompatible versions to get installed.

**Comment by altendky** [comment]
kicking ci for a fresh run

**Comment by altendky** [comment]
https://github.com/MagicStack/uvloop/actions/runs/3905648871/jobs/6672910215#step:8:982
```python-traceback
Traceback (most recent call last):
  File "/Users/runner/work/uvloop/uvloop/tests/test_base.py", line 220, in test_call_later_rounding
    self.assertGreaterEqual(finished - started, 69)
AssertionError: 66 not greater than or equal to 69
```

**Review by fantix — APPROVED** [review]
Thanks! I think the failing test on 3.11 is related to #471 and I'll try to fix it there.

**Pull request merged**
