### PR TITLE
Fixes #269

### LINKED ISSUE #269: RuntimeError: cannot convert sockaddr into Python object
* **uvloop**: 0.13.0
* **Python **: Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21)
* **Platform**: MacOS
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: yes

After installing `uvloop` as an event-loop factory my UDP server implementation stops working.

```
Unhandled exception in event loop
Traceback (most recent call last):
  File "uvloop/handles/udp.pyx", line 335, in uvloop.loop.__uv_udp_on_receive
  File "uvloop/dns.pyx", line 63, in uvloop.loop.__convert_sockaddr_to_pyaddr
RuntimeError: cannot convert sockaddr into Python object
```

That's because [__convert_sockaddr_to_pyaddr](https://github.com/MagicStack/uvloop/blob/master/uvloop/dns.pyx#L25) not compatibles af_unix socket family I guess.

### PR DESCRIPTION
**Pull request by mosquito**
Copying cPython behaviour.

### CODE REVIEW

**Comment by mosquito** [comment]
@1st1 any thoughts?

**Comment by 1st1** [comment]
Looks good.  Can you write a unittest?

**Comment by 1st1** [comment]
Also if possible please rebase on top of latest uvloop

**Comment by 1st1** [comment]
Closing in favor of https://github.com/MagicStack/uvloop/pull/286 (you're a co-author)

**Pull request closed without merging**
