### PR TITLE
Fix #169: asyncio.base_futures.InvalidStateError: invalid state

### LINKED ISSUE #169: asyncio.base_futures.InvalidStateError: invalid state
* **uvloop version**: 0.10.1
* **Python version**: 3.6.5
* **Platform**: Ubuntu 16.04
* **Can you reproduce the bug with `PYTHONASYNCIODEBUG` in env?**: No

I work with a raw sockets using `asyncio.Lock` to isolate blocks reading and `sock_recv` to communicate inside a Lock section.
In a random time first of all I get the following stacktrace:
```
Exception in callback Loop._sock_recv
handle: <Handle Loop._sock_recv>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 76, in uvloop.loop.Handle._run
  File "uvloop/loop.pyx", line 888, in uvloop.loop.Loop._sock_recv
asyncio.base_futures.InvalidStateError: invalid state
```

After that there is a problem with acquiring the Lock: it becomes pass any simultaneously calls.

Now very small information, but I'll try to investigate and reproduce it. And give you more details. But maybe you have a thoughts already?

### PR DESCRIPTION
**Pull request by andr-04**

### CODE REVIEW

**Comment by andr-04** [comment]
Actually, this is not correct behavior yet, I'm testing the additional patch now. Stay tuned please.

**Comment by andr-04** [comment]
ee13f17bd90ffa9c8946ff3d736f6cbbc8772cd5 not helped yet. @1st1, if you have an idea why -- let me know.

**Comment by 1st1** [comment]
I made a new PR that is essentially a refactoring of your fix and another unittest: https://github.com/MagicStack/uvloop/pull/173

**Comment by 1st1** [comment]
Closing in favour of #173

**Pull request closed without merging**
