### PR TITLE
Update Cython for 3.8 compatibility

### PR DESCRIPTION
**Pull request by dmontagu**
Maybe this solves https://github.com/MagicStack/uvloop/issues/266?

### CODE REVIEW

**Comment by LiraNuna** [comment]
Related: [Cython's changelog](https://github.com/cython/cython/blob/master/CHANGES.rst#02912-2019-07-07), showing that version 0.29.12 fixed this bug.

**Comment by nwalsh1995** [comment]
Hi, with the official release of Python 3.8 it would be nice if this got some more action! I was able to get uvloop to compile with the newest version of Cython as well.

**Comment by h1nk** [comment]
Even with the Cython version update as made in this PR (insurgency/aioa2squery@48683f0) uvloop installs in a fresh 3.8 environment fail ([see](https://github.com/insurgency/aioa2squery/runs/262029394#step:4:2253)). Are these changes confirmed to work for any other 3.8 users?

**Comment by atezerjani** [comment]
> Even with the Cython version update as made in this PR ([insurgency/aioa2squery@48683f0](https://github.com/insurgency/aioa2squery/commit/48683f0)) uvloop installs in a fresh 3.8 environment fail ([see](https://github.com/insurgency/aioa2squery/runs/262029394#step:4:2253)). Are these changes confirmed to work for any other 3.8 users?

It is also failing for me on python3.8

**Comment by dmontagu** [comment]
@h1nk @atezerjani You'd have to build it from scratch (the way it works if you follow the build instructions in the repo). Otherwise, you get the source distribution, which includes the already-cythonized C code, which won't due to the cython version.

You can confirm the build works with this update via:
```
docker run -it --rm python:3.8 /bin/bash

cd $HOME
git clone --recursive https://github.com/MagicStack/uvloop.git
cd uvloop

cat > requirements.dev.txt <<EOF
Cython==0.29.13
Sphinx>=1.4.1
psutil
pyOpenSSL==18.0.0
flake8>=3.7.5
EOF

pip install -r requirements.dev.txt
make
```

I'm not sure the tests are working properly though. I'm currently running
```
make test
```
right at the end of the above, and it seems to be stuck on `test_sock_cancel_add_reader_race`. But maybe I just haven't given it enough time.

**Comment by 1st1** [comment]
Could you please rebase on top of latest master?

**Comment by dmontagu** [comment]
Done -- although feel free to close this PR and merge your own if other minor changes are necessary and you don't want to block on me (I don't need credit for this lol).

**Comment by 1st1** [comment]
Updated in https://github.com/MagicStack/uvloop/commit/65c1a045b5c0e724a5a16747f308ecf70ebac68c

Thank you!

**Comment by dmontagu** [comment]
Awesome, thank you!

**Pull request closed without merging**
