### PR TITLE
fix test_renegotiation

### PR DESCRIPTION
**Pull request by fantix**
- [ ] fix test in Travis

### CODE REVIEW

**Comment by 1st1** [comment]
Beautiful, thanks, Fantix! Any other places to fix tests like that in uvloop?

**Comment by fantix** [comment]
Searched the code base, found a few `PROTOCOL_SSLv23` - the most widely-used one is in `_create_server_ssl_context`. I think we could replace it with `PROTOCOL_TLS` when [Python 3.5](https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_SSLv23) support is dropped (unlikely?), or do you prefer supporting both?

**Comment by 1st1** [comment]
> or do you prefer supporting both?

We probably need to support 3.5 for this upcoming release and then we can sunset it.

**Comment by 1st1** [comment]
>  I think we could replace it with PROTOCOL_TLS when Python 3.5 

Can we do that now and keep using `PROTOCOL_SSLv23` for 3.5? Is this a good idea?

**Comment by fantix** [comment]
Yeah sure, just a sec

**Pull request merged**
